apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-profile
  template:
    metadata:
      labels:
        app: user-profile
    spec:
      containers:
        - name: user-profile
          image: hilalseyhann/user-profile:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://bbuser:bbuser@postgres-db:5432/cloud_harmony_db"
